const locationData = {
    "ANDHRA PRADESH": {
        "ANANTAPUR": ["ANANTAPUR", "DHARMAVARAM", "HINDUPUR"],
        "CHITTOOR": ["CHITTOOR", "TIRUPATI", "MADANAPALLE"],
        "GUNTUR": ["GUNTUR", "TENALI", "NARASARAOPET"],
        "KRISHNA": ["VIJAYAWADA", "MACHILIPATNAM", "GUDIVADA"]
    },
    "TELANGANA": {
        "HYDERABAD": ["AMBERPET", "KHAIRATABAD", "SECUNDERABAD", "CHARMINAR"],
        "RANGAREDDY": ["SHAMSHABAD", "RAJENDRANAGAR", "SERILINGAMPALLY", "CHEVELLA"],
        "MEDCHAL-MALKAJGIRI": ["MEDCHAL", "MALKAJGIRI", "QUTHBULLAPUR", "UPPAL"],
        "WARANGAL": ["WARANGAL", "HANAMKONDA", "KAZIPET"]
    },
    "KARNATAKA": {
        "BELAGAVI": ["BELAGAVI", "GOKAK", "HUKKERI", "CHIKODI", "ATHANI", "SAUNDATTI", "RAMDURG", "BAILHONGAL", "KHANAPUR", "RAYBAG"],
        "BENGALURU URBAN": ["BENGALURU NORTH", "BENGALURU SOUTH", "ANEKAL", "YELAHANKA"],
        "DHARWAD": ["DHARWAD", "HUBBALLI", "KALGHATGI", "NAVALGUND", "KUNDGOL"],
        "MYSURU": ["MYSURU", "HUNSUR", "NANJANGUD", "PERIYAPATNA"]
    },
    "MAHARASHTRA": {
        "KOLHAPUR": ["KARVEER", "PANHALA", "SHAHUWADI", "KAGAL", "HATKANANGALE", "SHIROL", "RADHANAGARI", "GAGANBAVADA", "BHUDARGAD", "GADHINGLAJ", "CHANDGAD", "AJARA"],
        "PUNE": ["PUNE CITY", "HAVELI", "KHED", "BARAMATI", "JUNNAR", "SHIRUR", "INDAPUR", "DAUND", "MAVAL", "MULSHI"],
        "MUMBAI": ["MUMBAI CITY", "MUMBAI SUBURBAN"],
        "SATARA": ["SATARA", "KARAD", "WAI", "MAHABALESHWAR"]
    },
    "GOA": {
        "NORTH GOA": ["BARDEZ", "BICHOLIM", "PERNEM", "PONDA", "SATTARI", "TISWADI"],
        "SOUTH GOA": ["CANACONA", "MORMUGAO", "QUEPEM", "SALCETE", "SANGUEM", "DHARBANDORA"]
    }
};